.TH UNIFONTCHOJUNG 1 "2012 Mar 02"
.SH NAME
unifontchojung \- Extract Hangul syllables that have no final consonant
.SH SYNOPSIS
.br
.B unifontchojung
<
.I input-font.hex
>
.I output-font.hex
.SH DESCRIPTION
.B unifontchojung
reads a Unifont-format .hex font file from stdin and writes
a Unifont .hex file containing a subset to stdout.
The subset that is output only contains syllables that contain
an initial consonant (chojung) plus middle vowel (jungseong),
with no final consonant (jongseong).
This lets a font designer focus on this subset during font creation.
.PP
.SH FILES
.TP 15
*.bdf font files
.SH SEE ALSO
.BR bdfimplode (1),
.BR hex2bdf (1),
.BR hex2bdf-split (1),
.BR hex2sfd (1),
.BR hexbraille (1),
.BR hexdraw (1),
.BR hexmerge (1),
.BR johab2ucs2 (1),
.BR unibdf2hex (1),
.BR unifontpic (1),
.BR unibmp2hex (1),
.BR unicoverage (1),
.BR unidup (1),
.BR unifontksx (1),
.BR unigencircles (1),
.BR unigenwidth (1),
.BR unihex2bmp (1),
.BR unihexgen (1),
.BR unipagecount (1),
.BR uniunmask (1)
.SH AUTHOR
.B unifontchojung
was written in 2012 by Paul Hardy.
.SH LICENSE
.B unifontchojung
is licensed under the GNU General Public License version 2, or
(at your option) a later version.
.SH BUGS
No known bugs exist.
